### ISSUE TITLE
Local path

### ISSUE THREAD

**Issue by OmarNunezG** [NicKravchenko/base-de-datos-paqueteria#1]
You got a local path on
https://github.com/NicKravchenko/base-de-datos-paqueteria/blob/9578aa525e56dfe23b7382a64154f99117108163/Paquetera_DBNormalDataInsertion.sql#L13

I know you noticed and added
https://github.com/NicKravchenko/base-de-datos-paqueteria/blob/9578aa525e56dfe23b7382a64154f99117108163/Paquetera_DBNormalDataInsertion.sql#L3

But is there any chance you able this script to work with a relative one?

This could be a problem if someone does not get noticed and runs the script.

**Comment by NicKravchenko** [comment]
Nope, as Im concerned. Server executes t-sql and doesn't have an acces to a location where the client loaded the file from. So we need to have the path embedded within the script.
